"""
Django Ninja API configuration.
"""

from django.http import HttpRequest
from ninja import NinjaAPI
from ninja.errors import HttpError

from apps.accounts.api import router as auth_router
from apps.billing.api import router as billing_router

api = NinjaAPI(
    title="B2B SaaS Starter API",
    version="1.0.0",
    description="B2B SaaS API with Stytch authentication and Stripe billing.",
    openapi_extra={
        "info": {
            "contact": {"name": "API Support"},
        },
        "tags": [
            {
                "name": "auth",
                "description": "Magic link authentication and session management",
            },
            {
                "name": "billing",
                "description": "Subscription management and billing",
            },
            {
                "name": "health",
                "description": "Service health and readiness checks",
            },
        ],
        # Note: securitySchemes auto-generated by HttpBearer auth class
    },
)


@api.exception_handler(HttpError)
def http_error_handler(request: HttpRequest, exc: HttpError):
    """
    Convert HttpError to consistent ErrorResponse format.

    Ensures all error responses have {"detail": "..."} shape.
    """
    return api.create_response(
        request,
        {"detail": str(exc.message)},
        status=exc.status_code,
    )


# Register routers
api.add_router("/auth", auth_router)
api.add_router("/billing", billing_router)


@api.get("/health", tags=["health"], operation_id="healthCheck", summary="Health check")
def health_check(request: HttpRequest) -> dict:
    """Health check endpoint for load balancer."""
    return {"status": "ok"}

