"""
Django Ninja API configuration.
"""

from django.http import HttpRequest
from ninja import NinjaAPI
from ninja.errors import HttpError

from apps.accounts.api import router as auth_router
from apps.billing.api import router as billing_router
from apps.devices.api import router as devices_router
from apps.media.api import router as media_router
from apps.passkeys.api import router as passkeys_router
from apps.sms.api import router as sms_router
from apps.webhooks.api import router as webhooks_router
from apps.webhooks.hooks_api import router as hooks_router

api = NinjaAPI(
    title="B2B SaaS Starter API",
    version="1.0.0",
    description="B2B SaaS API with Stytch authentication and Stripe billing.",
    openapi_extra={
        "info": {
            "contact": {"name": "API Support"},
        },
        "tags": [
            {
                "name": "auth",
                "description": "Magic link authentication and session management",
            },
            {
                "name": "billing",
                "description": "Subscription management and billing",
            },
            {
                "name": "media",
                "description": "Image uploads for avatars and logos",
            },
            {
                "name": "passkeys",
                "description": "WebAuthn passkey authentication",
            },
            {
                "name": "devices",
                "description": "Mobile device linking and management",
            },
            {
                "name": "webhooks",
                "description": "Customer webhook endpoint management",
            },
            {
                "name": "hooks",
                "description": "REST Hooks API for Zapier/Make integrations",
            },
            {
                "name": "Phone Verification",
                "description": "SMS OTP phone verification",
            },
            {
                "name": "health",
                "description": "Service health and readiness checks",
            },
        ],
        # Note: securitySchemes auto-generated by HttpBearer auth class
    },
)


@api.exception_handler(HttpError)
def http_error_handler(request: HttpRequest, exc: HttpError):
    """
    Convert HttpError to consistent ErrorResponse format.

    Ensures all error responses have {"detail": "..."} shape.
    """
    return api.create_response(
        request,
        {"detail": str(exc.message)},
        status=exc.status_code,
    )


# Register routers
api.add_router("/auth", auth_router)
api.add_router("/billing", billing_router)
api.add_router("/media", media_router)
api.add_router("/auth/passkeys", passkeys_router)
api.add_router("/auth/phone", sms_router)
api.add_router("/webhooks", webhooks_router)
api.add_router("/hooks", hooks_router)
api.add_router("/devices", devices_router)


@api.get("/health", tags=["health"], operation_id="healthCheck", summary="Health check")
def health_check(request: HttpRequest) -> dict:
    """Health check endpoint for load balancer."""
    return {"status": "ok"}
