# Generated by Django 6.0 on 2026-01-05 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passkeys', '0001_create_passkey_model'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS django_cache (
                cache_key VARCHAR(255) NOT NULL PRIMARY KEY,
                value TEXT NOT NULL,
                expires TIMESTAMP NOT NULL
            );
            CREATE INDEX IF NOT EXISTS django_cache_expires_idx ON django_cache (expires);
            """,
            reverse_sql="DROP TABLE IF EXISTS django_cache;",
        ),
    ]
