# Generated by Django 6.0 on 2026-01-05 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passkeys", "0001_create_passkey_model"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                CREATE TABLE IF NOT EXISTS "django_cache" (
                    "cache_key" varchar(255) NOT NULL PRIMARY KEY,
                    "value" text NOT NULL,
                    "expires" timestamp with time zone NOT NULL
                );
                CREATE INDEX IF NOT EXISTS "django_cache_expires"
                    ON "django_cache" ("expires");
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS "django_cache_expires";
                DROP TABLE IF EXISTS "django_cache";
            """,
        ),
    ]
