# Generated by Django 6.0 on 2026-01-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.CharField(db_index=True, max_length=50)),
                ("event_id", models.CharField(max_length=255)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["processed_at"], name="core_proces_process_2a4bdc_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "event_id"), name="unique_webhook_event"
                    )
                ],
            },
        ),
    ]
