# Generated by Django 6.0 on 2026-01-03 20:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, help_text="Action type, e.g. 'member.role_changed'", max_length=100)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.CharField(max_length=100)),
                ('organization_id', models.CharField(db_index=True, max_length=100)),
                ('actor_id', models.CharField(db_index=True, help_text='User or system ID that performed the action', max_length=100)),
                ('actor_email', models.EmailField(blank=True, help_text='Actor email (denormalized for display)', max_length=254)),
                ('correlation_id', models.UUIDField(blank=True, db_index=True, help_text='Request trace ID for correlation', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Client user agent string')),
                ('diff', models.JSONField(blank=True, default=dict, help_text="Field-level changes: {'old': {...}, 'new': {...}}")),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (method, path, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'created_at'], name='events_audi_organiz_6f29d4_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='events_audi_aggrega_92f909_idx'), models.Index(fields=['actor_id'], name='events_audi_actor_i_ef3de5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique event identifier for consumer idempotency', unique=True)),
                ('event_type', models.CharField(db_index=True, help_text="Event type, e.g. 'member.invited'", max_length=100)),
                ('aggregate_type', models.CharField(help_text="Entity type, e.g. 'member'", max_length=50)),
                ('aggregate_id', models.CharField(help_text="Entity ID, e.g. 'mbr_01HN...'", max_length=100)),
                ('organization_id', models.CharField(db_index=True, help_text='Tenant organization ID', max_length=100)),
                ('schema_version', models.PositiveIntegerField(default=1, help_text='Payload schema version for evolution')),
                ('payload', models.JSONField(help_text='Complete event data including actor, data, correlation_id, etc.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the event was successfully published', null=True)),
                ('attempts', models.PositiveIntegerField(default=0, help_text='Number of publish attempts')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, help_text='When to retry publishing (for exponential backoff)', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message from failed publish attempt')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='events_outb_status_9dabce_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='events_outb_aggrega_11f4b9_idx')],
            },
        ),
    ]
