# Generated by Django 6.0 on 2026-01-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="event_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Source OutboxEvent ID for idempotency",
                null=True,
                unique=True,
            ),
        ),
    ]
