# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_add_publishing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the event was claimed for publishing (for stuck-event recovery)",
                null=True,
            ),
        ),
    ]
