# Generated by Django 6.0 on 2026-01-23 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0012_alter_member_deleted_at"),
        ("organizations", "0006_alter_organization_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("idempotency_key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("device_id", models.CharField(max_length=64)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(max_length=32)),
                (
                    "intent",
                    models.CharField(
                        choices=[("create", "Create"), ("update", "Update"), ("delete", "Delete")],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField()),
                ("client_timestamp", models.DateTimeField()),
                ("server_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applied", "Applied"),
                            ("rejected", "Rejected"),
                            ("conflict", "Conflict"),
                            ("duplicate", "Duplicate"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("resolution_details", models.JSONField(blank=True, null=True)),
                (
                    "drift_ms",
                    models.IntegerField(
                        blank=True, help_text="client_timestamp - server_timestamp in ms", null=True
                    ),
                ),
                (
                    "conflict_fields",
                    models.JSONField(
                        blank=True,
                        help_text="Fields that had conflicts (for field-level LWW)",
                        null=True,
                    ),
                ),
                (
                    "client_retry_count",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Times client retried this op"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sync_operations",
                        to="accounts.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_operations",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-server_timestamp"],
                "indexes": [
                    models.Index(
                        fields=["organization", "server_timestamp"],
                        name="sync_syncop_organiz_44c7be_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"], name="sync_syncop_entity__6c4e61_idx"
                    ),
                ],
            },
        ),
    ]
