# Generated by Django 6.0 on 2026-01-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncoperation",
            name="entity_id",
            field=models.CharField(max_length=36),
        ),
    ]
