# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sync", "0002_uuid7_migration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syncoperation",
            name="idempotency_key",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
