# Generated by Django 6.0 on 2025-12-29 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_add_use_billing_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(db_index=True, help_text="Stripe subscription ID, e.g. 'sub_xxx'", max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(help_text="Stripe price ID, e.g. 'price_xxx'", max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='incomplete', help_text='Subscription status from Stripe', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of seats (synced with member count)')),
                ('current_period_start', models.DateTimeField(help_text='Start of current billing period')),
                ('current_period_end', models.DateTimeField(help_text='End of current billing period (next invoice date)')),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='If True, subscription will cancel at period end')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
