# Generated by Django 6.0 on 2026-01-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual (UI/API)'), ('zapier', 'Zapier'), ('make', 'Make'), ('rest_hooks', 'REST Hooks (generic)')], default='manual', help_text='How this endpoint was created (manual, zapier, make, rest_hooks)', max_length=20),
        ),
    ]
