# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webhooks", "0002_add_source_to_webhook_endpoint"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="webhookdelivery",
            name="webhooks_we_event_i_35fb55_idx",
        ),
    ]
