# Generated by Django 6.0 on 2025-12-28 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stytch_user_id',
        ),
    ]
