# Generated by Django 6.0 on 2026-01-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_member_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, default='', help_text="URL to user's avatar image"),
        ),
    ]
