# Generated by Django 6.0 on 2026-01-01 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_user_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Phone number in E.164 format (e.g., +14155551234)",
                max_length=20,
            ),
        ),
    ]
