# Generated by Django 6.0 on 2026-01-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_access_token',
            field=models.TextField(blank=True, default='', help_text='Encrypted Google access token for Directory API'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_refresh_token',
            field=models.TextField(blank=True, default='', help_text='Encrypted Google refresh token'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_token_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the Google access token expires', null=True),
        ),
    ]
