# Generated by Django 6.0 on 2026-01-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_make_google_tokens_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when phone was verified via OTP. NULL = unverified.', null=True),
        ),
    ]
