# Generated by Django 6.0 on 2026-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_add_member_organization_deleted_at_index"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="member",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                fields=("user", "organization"), name="unique_member_per_org"
            ),
        ),
    ]
