# Generated by Django 6.0 on 2026-01-18 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_alter_member_unique_together_and_more"),
        ("organizations", "0005_add_soft_delete"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="member",
            name="unique_member_per_org",
        ),
        migrations.AddConstraint(
            model_name="member",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user", "organization"),
                name="unique_member_per_org",
            ),
        ),
    ]
