# Generated by Django 6.0.2 on 2026-02-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_member_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        db_index=True,
                        help_text="OAuth provider identifier (e.g., google, github, microsoft)",
                        max_length=50,
                    ),
                ),
                (
                    "provider_subject",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Provider-specific user identifier (e.g., Google sub claim)",
                        max_length=255,
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, help_text="Last time this provider's token was used", null=True
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connected_accounts",
                        to="accounts.member",
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "provider"), name="unique_provider_per_member"
                    )
                ],
            },
        ),
    ]
