# Generated by Django 6.0.2 on 2026-02-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_connected_account"),
        ("organizations", "0008_slug_unique_only_for_active_orgs"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["organization", "role", "deleted_at"], name="accounts_me_organiz_efad86_idx"
            ),
        ),
    ]
