# Generated by Django 6.0 on 2026-01-22 20:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0011_fix_member_unique_constraint_for_soft_delete"),
        ("organizations", "0005_add_soft_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_uuid",
                    models.CharField(
                        db_index=True,
                        help_text="Unique device identifier from iOS Keychain / Android",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Device name (e.g., 'iPhone 15 Pro')", max_length=100
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        help_text="Platform identifier (e.g., 'ios', 'android')", max_length=20
                    ),
                ),
                (
                    "os_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Operating system version (e.g., '17.2')",
                        max_length=20,
                    ),
                ),
                (
                    "app_version",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="App version (e.g., '1.0.0')",
                        max_length=20,
                    ),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when device was revoked. NULL = active.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this device",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "revoked_at"], name="devices_dev_user_id_993fa6_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DeviceLinkToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 hash of the JWT token",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, help_text="Token expiration timestamp"),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when token was used. NULL = unused.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        help_text="Member context for initial session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_link_tokens",
                        to="accounts.member",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="Organization context for initial session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_link_tokens",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated the link",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_link_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "expires_at"], name="devices_dev_user_id_f001af_idx"
                    )
                ],
            },
        ),
    ]
