# Generated by Django 6.0 on 2026-01-01 17:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0004_organization_logo_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        help_text="S3 key or local path to the file", max_length=500, unique=True
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[("avatar", "Avatar"), ("logo", "Logo"), ("other", "Other")],
                        max_length=20,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(help_text="MIME type of the image", max_length=100),
                ),
                ("size_bytes", models.PositiveIntegerField(help_text="File size in bytes")),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that owns this image (for logos)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_images",
                        to="organizations.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this image",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who owns this image (for avatars)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "image_type"], name="media_uploa_user_id_ece994_idx"
                    ),
                    models.Index(
                        fields=["organization", "image_type"], name="media_uploa_organiz_a8bcbf_idx"
                    ),
                ],
            },
        ),
    ]
