# Generated by Django 6.0.2 on 2026-02-06 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media", "0001_initial"),
        ("organizations", "0006_alter_organization_deleted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="uploadedimage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("organization__isnull", True), ("user__isnull", False)),
                    models.Q(("organization__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="uploaded_image_single_owner",
            ),
        ),
    ]
