import { writeFileSync } from "node:fs";
import { join } from "node:path";

export interface EnvConfig {
  project: {
    displayName: string;
    prefix: string;
    domain?: string;
    apiDomain?: string;
  };
  secrets: {
    djangoSecretKey: string;
    fieldEncryptionKey: string;
  };
  services: {
    stytchProjectId?: string;
    stytchSecret?: string;
    stytchWebhookSecret?: string;
    stytchPublicToken?: string;
    stripeSecretKey?: string;
    stripePublishableKey?: string;
    stripePriceId?: string;
    stripeWebhookSecret?: string;
    resendApiKey?: string;
    googlePlacesApiKey?: string;
  };
}

export function generateBackendEnv(rootDir: string, config: EnvConfig): string {
  const filePath = join(rootDir, "backend", ".env");

  const lines = [
    "# Generated by pikaia-setup",
    "",
    "# Django",
    `SECRET_KEY=${config.secrets.djangoSecretKey}`,
    "DEBUG=True",
    "ALLOWED_HOSTS=localhost,127.0.0.1",
    "",
    "# Database",
    `DATABASE_URL=postgresql://postgres:postgres@localhost:5432/${config.project.prefix}`,
    "",
    "# Application branding",
    `APP_SLUG=${config.project.prefix}`,
    `DEVICE_LINK_URL_SCHEME=${config.project.prefix}://device/link`,
    "",
    "# WebAuthn (Passkeys)",
    "WEBAUTHN_RP_ID=localhost",
    `WEBAUTHN_RP_NAME=${config.project.displayName}`,
    "WEBAUTHN_ORIGIN=http://localhost:5173",
    "",
    "# Stytch (https://stytch.com/dashboard)",
    `STYTCH_PROJECT_ID=${config.services.stytchProjectId || ""}`,
    `STYTCH_SECRET=${config.services.stytchSecret || ""}`,
    `STYTCH_WEBHOOK_SECRET=${config.services.stytchWebhookSecret || ""}`,
    "",
    "# Stytch Trusted Auth Token (for passkey -> Stytch session)",
    "STYTCH_TRUSTED_AUTH_PROFILE_ID=",
    "STYTCH_TRUSTED_AUTH_AUDIENCE=stytch",
    "STYTCH_TRUSTED_AUTH_ISSUER=passkey-auth",
    "PASSKEY_JWT_PRIVATE_KEY=",
    "",
    "# Stripe (https://dashboard.stripe.com/test/apikeys)",
    `STRIPE_SECRET_KEY=${config.services.stripeSecretKey || ""}`,
    `STRIPE_WEBHOOK_SECRET=${config.services.stripeWebhookSecret || ""}`,
    `STRIPE_PRICE_ID=${config.services.stripePriceId || ""}`,
    "",
    "# Resend (https://resend.com/api-keys)",
    `RESEND_API_KEY=${config.services.resendApiKey || ""}`,
    "",
    "# Field Encryption",
    `FIELD_ENCRYPTION_KEY=${config.secrets.fieldEncryptionKey}`,
    "",
  ];

  writeFileSync(filePath, lines.join("\n"));
  return filePath;
}

export function generateFrontendEnv(
  rootDir: string,
  config: EnvConfig,
): string {
  const filePath = join(rootDir, "frontend", ".env");

  const lines = [
    "# Generated by pikaia-setup",
    "",
    "# Stytch (get from https://stytch.com/dashboard - Configuration > SDK Config)",
    `VITE_STYTCH_PUBLIC_TOKEN=${config.services.stytchPublicToken || ""}`,
    "",
    "# Backend API URL",
    "VITE_API_URL=http://localhost:8000/api/v1",
    "",
    "# Google Places API (for address autocomplete)",
    `VITE_GOOGLE_PLACES_API_KEY=${config.services.googlePlacesApiKey || ""}`,
    "",
  ];

  writeFileSync(filePath, lines.join("\n"));
  return filePath;
}

export function generateDockerEnv(rootDir: string, config: EnvConfig): string {
  const filePath = join(rootDir, ".env.local");

  const lines = [
    "# Generated by pikaia-setup",
    `COMPOSE_PROJECT_NAME=${config.project.prefix}`,
    `POSTGRES_DB=${config.project.prefix}`,
    "",
  ];

  writeFileSync(filePath, lines.join("\n"));
  return filePath;
}

export function generateProductionEnv(
  rootDir: string,
  config: EnvConfig,
): string {
  const filePath = join(rootDir, ".env.production");

  const domain = config.project.domain || "app.example.com";

  const lines = [
    "# Generated by pikaia-setup",
    "# Upload to AWS Secrets Manager via: ./scripts/bootstrap-secrets.sh",
    "",
    "# Django",
    `DJANGO_SECRET_KEY=${config.secrets.djangoSecretKey}`,
    "",
    "# Application branding",
    `APP_SLUG=${config.project.prefix}`,
    "",
    "# WebAuthn / Passkeys",
    `WEBAUTHN_RP_ID=${domain}`,
    `WEBAUTHN_RP_NAME=${config.project.displayName}`,
    `WEBAUTHN_ORIGIN=https://${domain}`,
    "",
    "# CORS",
    `CORS_ALLOWED_ORIGINS=https://${domain}`,
    "",
    "# Stytch",
    `STYTCH_PROJECT_ID=${config.services.stytchProjectId || ""}`,
    `STYTCH_SECRET=${config.services.stytchSecret || ""}`,
    "",
    "# Stripe",
    `STRIPE_SECRET_KEY=${config.services.stripeSecretKey || ""}`,
    `STRIPE_PRICE_ID=${config.services.stripePriceId || ""}`,
    `STRIPE_WEBHOOK_SECRET=${config.services.stripeWebhookSecret || ""}`,
    "",
    "# Resend",
    `RESEND_API_KEY=${config.services.resendApiKey || ""}`,
    "",
    "# Stytch Trusted Auth Token",
    "STYTCH_TRUSTED_AUTH_PROFILE_ID=",
    "STYTCH_TRUSTED_AUTH_AUDIENCE=stytch",
    "STYTCH_TRUSTED_AUTH_ISSUER=passkey-auth",
    "PASSKEY_JWT_PRIVATE_KEY=",
    "",
    "# Field Encryption",
    `FIELD_ENCRYPTION_KEY=${config.secrets.fieldEncryptionKey}`,
    "",
  ];

  writeFileSync(filePath, lines.join("\n"));
  return filePath;
}
