# Generated by Django 6.0.2 on 2026-02-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="trial_ends_at",
            field=models.DateTimeField(
                blank=True, help_text="When the free trial expires (null = no trial)", null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_extended_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of times the trial has been extended"
            ),
        ),
    ]
