/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Health check endpoint for load balancer.
         */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send magic link email
         * @description Send a magic link email for discovery authentication.
         *
         *     Uses discovery flow - user authenticates first, then picks/creates org.
         */
        post: operations["sendMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/magic-link/authenticate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate magic link token
         * @description Authenticate a magic link token.
         *
         *     Returns an intermediate session token (IST) and list of
         *     organizations the user can join or create.
         */
        post: operations["authenticateMagicLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/discovery/create-org": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create new organization
         * @description Create a new organization from discovery flow.
         *
         *     Exchanges the IST for a session and creates the org.
         */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/discovery/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange IST for session
         * @description Exchange IST for session by joining an existing organization.
         */
        post: operations["exchangeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke current session
         * @description Revoke the current session.
         *
         *     Expects session JWT in Authorization header (Bearer <session_jwt>),
         *     consistent with other authenticated endpoints.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user info
         * @description Get current authenticated user, member, and organization info.
         *
         *     Requires valid session JWT in Authorization header.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update user profile
         * @description Update current user's profile (name only).
         *
         *     Updates local database and syncs to Stytch.
         *     Phone number changes require OTP verification via /phone/verify-otp.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v1/auth/phone/send-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send OTP to phone for verification
         * @description Send a one-time password (OTP) to the specified phone number.
         *
         *     The OTP is used to verify phone ownership before updating the user's profile.
         *     Uses Stytch's SMS OTP service.
         */
        post: operations["sendPhoneOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/phone/verify-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify phone OTP and update profile
         * @description Verify the OTP sent to the phone number.
         *
         *     On success, updates the user's phone number in both local database and Stytch.
         */
        post: operations["verifyPhoneOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/email/start-update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start email address update flow
         * @description Initiate email address change.
         *
         *     Sends a verification to the new email address. User must verify the new
         *     email to complete the change. The update is finalized via Stytch.
         */
        post: operations["startEmailUpdate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current organization details
         * @description Get current organization details including billing info.
         *
         *     All authenticated members can view.
         */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update organization settings
         * @description Update organization settings (name).
         *
         *     Admin only. Updates local database and syncs to Stytch.
         */
        patch: operations["updateOrganization"];
        trace?: never;
    };
    "/api/v1/auth/organization/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update organization billing info
         * @description Update organization billing info (address, VAT, etc.).
         *
         *     Admin only. This is our system's data - synced out to Stripe.
         */
        patch: operations["updateBilling"];
        trace?: never;
    };
    "/api/v1/auth/organization/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organization members
         * @description List all active members of the current organization.
         *
         *     Admin only.
         */
        get: operations["listMembers"];
        put?: never;
        /**
         * Invite a new member
         * @description Invite a new member to the organization.
         *
         *     Admin only. Stytch sends the invite email with Magic Link.
         */
        post: operations["inviteMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/organization/members/{member_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove member from organization
         * @description Remove a member from the organization.
         *
         *     Admin only. Cannot remove yourself. Soft deletes locally
         *     and removes from Stytch.
         */
        delete: operations["deleteMember"];
        options?: never;
        head?: never;
        /**
         * Update member role
         * @description Update a member's role (admin or member).
         *
         *     Admin only. Cannot change your own role.
         */
        patch: operations["updateMemberRole"];
        trace?: never;
    };
    "/api/v1/auth/directory/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Google Workspace directory for users
         * @description Search Google Workspace directory for coworkers.
         *
         *     Returns matching users from the authenticated user's Google Workspace domain.
         *     Only works if the user has signed in with Google OAuth and granted
         *     the Directory API scope. Returns empty list if not available.
         */
        get: operations["searchDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/directory/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Proxy Google Workspace avatar image
         * @description Proxy a Google Workspace avatar image.
         *
         *     Google Directory API avatar URLs require OAuth authentication.
         *     This endpoint fetches the image server-side and returns it.
         */
        get: operations["getDirectoryAvatar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stripe Checkout session
         * @description Create a Stripe Checkout session for subscribing.
         *
         *     Admin only. Returns URL to redirect user to Stripe Checkout.
         */
        post: operations["createCheckoutSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Stripe Customer Portal session
         * @description Create a Stripe Customer Portal session.
         *
         *     Admin only. Returns URL to redirect user to manage their subscription.
         */
        post: operations["createPortalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current subscription status
         * @description Get current subscription status.
         *
         *     Returns subscription details or 'none' status if not subscribed.
         */
        get: operations["getSubscription"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/subscription-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create subscription intent for Elements payment
         * @description Create a subscription with an incomplete payment intent.
         *
         *     Admin only. Returns client_secret for PaymentElement.
         *     Use this for embedded Stripe Elements payment flow.
         */
        post: operations["createSubscriptionIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/confirm-subscription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm subscription after payment
         * @description Sync subscription status from Stripe after payment.
         *
         *     Call this after confirmPayment succeeds to update local database.
         *     Useful for development without Stripe CLI webhooks.
         */
        post: operations["confirmSubscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organization invoices
         * @description List invoices from Stripe for the current organization.
         *
         *     Admin only. Returns invoices sorted by date (newest first).
         *     Use starting_after with an invoice ID for pagination.
         */
        get: operations["listInvoices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/upload-request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request an image upload URL
         * @description Request a presigned URL for uploading an image.
         *
         *     Returns upload URL and instructions. The client should:
         *     1. Upload the file to the returned URL using the specified method
         *     2. Call /confirm endpoint after successful upload
         */
        post: operations["requestImageUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an image upload
         * @description Confirm that an image was successfully uploaded.
         *
         *     Verifies the file exists in storage and saves metadata to the database.
         */
        post: operations["confirmImageUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/direct-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Direct upload for local development
         * @description Direct file upload endpoint for local development.
         *
         *     In production, files are uploaded directly to S3 using presigned URLs.
         *     This endpoint is only used in local development.
         */
        post: operations["directUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an uploaded image
         * @description Delete an uploaded image.
         *
         *     Users can only delete their own avatars.
         *     Admins can delete organization logos.
         */
        delete: operations["deleteImage"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * MessageResponse
         * @description Generic message response.
         * @example {
         *       "message": "Operation completed successfully."
         *     }
         */
        MessageResponse: {
            /**
             * Message
             * @description Human-readable status message
             */
            message: string;
        };
        /**
         * ErrorResponse
         * @description Standard error response format.
         * @example {
         *       "detail": "Invalid or expired token."
         *     }
         */
        ErrorResponse: {
            /**
             * Detail
             * @description Human-readable error message
             */
            detail: string;
        };
        /**
         * MagicLinkSendRequest
         * @description Request to send a magic link email.
         */
        MagicLinkSendRequest: {
            /**
             * Email
             * Format: email
             * @description User's email address for magic link delivery
             * @example user@company.com
             */
            email: string;
        };
        /**
         * DiscoveredOrganization
         * @description An organization the user can join.
         */
        DiscoveredOrganization: {
            /**
             * Organization Id
             * @description Stytch organization ID
             */
            organization_id: string;
            /**
             * Organization Name
             * @description Organization display name
             */
            organization_name: string;
            /**
             * Organization Slug
             * @description URL-safe organization identifier
             */
            organization_slug: string;
        };
        /**
         * MagicLinkAuthenticateResponse
         * @description Response after magic link authentication.
         * @example {
         *       "discovered_organizations": [
         *         {
         *           "organization_id": "organization-live-abc123",
         *           "organization_name": "Acme Corp",
         *           "organization_slug": "acme-corp"
         *         }
         *       ],
         *       "email": "user@company.com",
         *       "intermediate_session_token": "ist_xxx..."
         *     }
         */
        MagicLinkAuthenticateResponse: {
            /**
             * Intermediate Session Token
             * @description Token to exchange for a full session after org selection
             */
            intermediate_session_token: string;
            /**
             * Email
             * @description Authenticated user's email address
             */
            email: string;
            /**
             * Discovered Organizations
             * @description Organizations the user can join or already belongs to
             */
            discovered_organizations: components["schemas"]["DiscoveredOrganization"][];
        };
        /**
         * MagicLinkAuthenticateRequest
         * @description Request to authenticate a magic link token.
         */
        MagicLinkAuthenticateRequest: {
            /**
             * Token
             * @description Magic link token from the email URL query parameter
             * @example DOYoip3rvIMMW2A7LRLI4M3EjcxZ...
             */
            token: string;
        };
        /**
         * SessionResponse
         * @description Response containing session credentials after org selection.
         * @example {
         *       "member_id": "member-live-abc123",
         *       "organization_id": "organization-live-abc123",
         *       "session_jwt": "eyJhbGciOiJSUzI1NiI...",
         *       "session_token": "stytch_session_xxx..."
         *     }
         */
        SessionResponse: {
            /**
             * Session Token
             * @description Stytch session token for server-side use
             */
            session_token: string;
            /**
             * Session Jwt
             * @description JWT for Authorization header (Bearer token)
             */
            session_jwt: string;
            /**
             * Member Id
             * @description Stytch member ID within the organization
             */
            member_id: string;
            /**
             * Organization Id
             * @description Stytch organization ID
             */
            organization_id: string;
        };
        /**
         * DiscoveryCreateOrgRequest
         * @description Request to create a new org from discovery flow.
         */
        DiscoveryCreateOrgRequest: {
            /**
             * Intermediate Session Token
             * @description Intermediate session token from magic link authentication
             * @example ist_xxx...
             */
            intermediate_session_token: string;
            /**
             * Organization Name
             * @description Display name for the new organization
             * @example Acme Corp
             */
            organization_name: string;
            /**
             * Organization Slug
             * @description URL-safe identifier for the organization (lowercase, hyphens allowed)
             * @example acme-corp
             */
            organization_slug: string;
        };
        /**
         * DiscoveryExchangeRequest
         * @description Request to exchange IST for session (join existing org).
         */
        DiscoveryExchangeRequest: {
            /**
             * Intermediate Session Token
             * @description Intermediate session token from magic link authentication
             * @example ist_xxx...
             */
            intermediate_session_token: string;
            /**
             * Organization Id
             * @description Stytch organization ID to join
             * @example organization-live-abc123...
             */
            organization_id: string;
        };
        /**
         * MeResponse
         * @description Response for /auth/me endpoint with current session context.
         * @example {
         *       "member": {
         *         "id": 1,
         *         "is_admin": true,
         *         "role": "admin",
         *         "stytch_member_id": "member-live-abc123"
         *       },
         *       "organization": {
         *         "id": 1,
         *         "name": "Acme Corp",
         *         "slug": "acme-corp",
         *         "stytch_org_id": "organization-live-abc123"
         *       },
         *       "user": {
         *         "email": "user@company.com",
         *         "id": 1,
         *         "name": "Jane Doe"
         *       }
         *     }
         */
        MeResponse: {
            /** @description Cross-org user identity */
            user: components["schemas"]["UserInfo"];
            /** @description Org-scoped membership details */
            member: components["schemas"]["MemberInfo"];
            /** @description Current organization context */
            organization: components["schemas"]["OrganizationInfo"];
        };
        /**
         * MemberInfo
         * @description Member info for /auth/me response.
         */
        MemberInfo: {
            /**
             * Id
             * @description Local database member ID
             */
            id: number;
            /**
             * Stytch Member Id
             * @description Stytch member ID
             */
            stytch_member_id: string;
            /**
             * Role
             * @description Member's role within the organization (e.g., admin, member)
             */
            role: string;
            /**
             * Is Admin
             * @description Whether the member has admin privileges
             */
            is_admin: boolean;
        };
        /**
         * OrganizationInfo
         * @description Organization info for /auth/me response.
         */
        OrganizationInfo: {
            /**
             * Id
             * @description Local database organization ID
             */
            id: number;
            /**
             * Stytch Org Id
             * @description Stytch organization ID
             */
            stytch_org_id: string;
            /**
             * Name
             * @description Organization display name
             */
            name: string;
            /**
             * Slug
             * @description URL-safe organization identifier
             */
            slug: string;
            /**
             * Logo Url
             * @description URL to organization logo image
             * @default
             */
            logo_url: string;
        };
        /**
         * UserInfo
         * @description Current user info response.
         */
        UserInfo: {
            /**
             * Id
             * @description Local database user ID
             */
            id: number;
            /**
             * Email
             * @description User's email address
             */
            email: string;
            /**
             * Name
             * @description User's display name
             */
            name: string;
            /**
             * Avatar Url
             * @description URL to user's avatar image
             * @default
             */
            avatar_url: string;
            /**
             * Phone Number
             * @description Phone number in E.164 format
             * @default
             */
            phone_number: string;
        };
        /**
         * UpdateProfileRequest
         * @description Request to update user profile (name only).
         *
         *     Phone number changes require OTP verification via /phone/verify-otp.
         */
        UpdateProfileRequest: {
            /**
             * Name
             * @description User's display name
             * @example Jane Doe
             */
            name: string;
        };
        /**
         * PhoneOtpResponse
         * @description Response for phone OTP operations.
         */
        PhoneOtpResponse: {
            /**
             * Success
             * @description Whether the operation succeeded
             */
            success: boolean;
            /**
             * Message
             * @description Status message
             */
            message: string;
        };
        /**
         * SendPhoneOtpRequest
         * @description Request to send OTP to a phone number for verification.
         */
        SendPhoneOtpRequest: {
            /**
             * Phone Number
             * @description Phone number in E.164 format
             * @example +14155551234
             */
            phone_number: string;
        };
        /**
         * VerifyPhoneOtpRequest
         * @description Request to verify a phone OTP.
         */
        VerifyPhoneOtpRequest: {
            /**
             * Phone Number
             * @description Phone number that received the OTP
             */
            phone_number: string;
            /**
             * Otp Code
             * @description 6-digit OTP code
             * @example 123456
             */
            otp_code: string;
        };
        /**
         * EmailUpdateResponse
         * @description Response for email update initiation.
         */
        EmailUpdateResponse: {
            /**
             * Success
             * @description Whether the update was initiated
             */
            success: boolean;
            /**
             * Message
             * @description Status message
             */
            message: string;
        };
        /**
         * StartEmailUpdateRequest
         * @description Request to start email update flow.
         */
        StartEmailUpdateRequest: {
            /**
             * New Email
             * Format: email
             * @description New email address to change to
             * @example newemail@example.com
             */
            new_email: string;
        };
        /**
         * BillingAddressSchema
         * @description Billing address for organization.
         */
        BillingAddressSchema: {
            /**
             * Line1
             * @description Street address line 1
             * @default
             */
            line1: string;
            /**
             * Line2
             * @description Street address line 2
             * @default
             */
            line2: string;
            /**
             * City
             * @description City
             * @default
             */
            city: string;
            /**
             * State
             * @description State/Province/Region
             * @default
             */
            state: string;
            /**
             * Postal Code
             * @description Postal/ZIP code
             * @default
             */
            postal_code: string;
            /**
             * Country
             * @description ISO 3166-1 alpha-2 country code
             * @default
             * @example US
             * @example DE
             * @example PL
             */
            country: string;
        };
        /**
         * BillingInfoResponse
         * @description Organization billing info response.
         */
        BillingInfoResponse: {
            /**
             * Use Billing Email
             * @description If True, invoices sent to billing_email; otherwise to admin
             */
            use_billing_email: boolean;
            /**
             * Billing Email
             * @description Email for invoices
             */
            billing_email: string;
            /**
             * Billing Name
             * @description Legal/company name
             */
            billing_name: string;
            /** @description Billing address */
            address: components["schemas"]["BillingAddressSchema"];
            /**
             * Vat Id
             * @description EU VAT number
             */
            vat_id: string;
        };
        /**
         * OrganizationDetailResponse
         * @description Full organization details response.
         */
        OrganizationDetailResponse: {
            /**
             * Id
             * @description Local database ID
             */
            id: number;
            /**
             * Stytch Org Id
             * @description Stytch organization ID
             */
            stytch_org_id: string;
            /**
             * Name
             * @description Organization display name
             */
            name: string;
            /**
             * Slug
             * @description URL-safe identifier
             */
            slug: string;
            /**
             * Logo Url
             * @description URL to organization logo image
             * @default
             */
            logo_url: string;
            /** @description Billing information */
            billing: components["schemas"]["BillingInfoResponse"];
        };
        /**
         * UpdateOrganizationRequest
         * @description Request to update organization settings (admin only).
         */
        UpdateOrganizationRequest: {
            /**
             * Name
             * @description Organization display name
             * @example Acme Corp
             */
            name: string;
            /**
             * Slug
             * @description URL-safe identifier for the organization (2-128 chars, lowercase)
             * @example acme-corp
             */
            slug?: string | null;
        };
        /**
         * UpdateBillingRequest
         * @description Request to update organization billing info (admin only).
         */
        UpdateBillingRequest: {
            /**
             * Use Billing Email
             * @description If True, send invoices to billing_email; otherwise send to admin
             * @default false
             */
            use_billing_email: boolean;
            /**
             * Billing Email
             * @description Email for invoices (used only if use_billing_email is True)
             * @example billing@company.com
             */
            billing_email?: string | null;
            /**
             * Billing Name
             * @description Legal/company name for invoices
             * @default
             * @example Acme Corporation Inc.
             */
            billing_name: string;
            /** @description Billing address */
            address?: components["schemas"]["BillingAddressSchema"] | null;
            /**
             * Vat Id
             * @description EU VAT number
             * @default
             * @example DE123456789
             */
            vat_id: string;
        };
        /**
         * MemberListItem
         * @description Member info for list response.
         */
        MemberListItem: {
            /**
             * Id
             * @description Local database member ID
             */
            id: number;
            /**
             * Stytch Member Id
             * @description Stytch member ID
             */
            stytch_member_id: string;
            /**
             * Email
             * @description Member's email address
             */
            email: string;
            /**
             * Name
             * @description Member's display name
             */
            name: string;
            /**
             * Role
             * @description Member's role (admin or member)
             */
            role: string;
            /**
             * Is Admin
             * @description Whether member has admin privileges
             */
            is_admin: boolean;
            /**
             * Status
             * @description Member status (active, invited)
             */
            status: string;
            /**
             * Created At
             * @description When the member joined (ISO format)
             */
            created_at: string;
        };
        /**
         * MemberListResponse
         * @description Response containing list of organization members.
         */
        MemberListResponse: {
            /**
             * Members
             * @description List of active organization members
             */
            members: components["schemas"]["MemberListItem"][];
        };
        /**
         * InviteMemberResponse
         * @description Response after inviting a member.
         */
        InviteMemberResponse: {
            /**
             * Message
             * @description Success message
             */
            message: string;
            /**
             * Stytch Member Id
             * @description Stytch member ID of invited member
             */
            stytch_member_id: string;
        };
        /**
         * InviteMemberRequest
         * @description Request to invite a new member to the organization.
         */
        InviteMemberRequest: {
            /**
             * Email
             * Format: email
             * @description Email address of the member to invite
             * @example newuser@example.com
             */
            email: string;
            /**
             * Name
             * @description Optional display name for the member
             * @default
             * @example Jane Doe
             */
            name: string;
            /**
             * Role
             * @description Role to assign: 'admin' or 'member'
             * @default member
             * @example member
             */
            role: string;
        };
        /**
         * UpdateMemberRoleRequest
         * @description Request to update a member's role.
         */
        UpdateMemberRoleRequest: {
            /**
             * Role
             * @description New role: 'admin' or 'member'
             * @example admin
             */
            role: string;
        };
        /**
         * DirectoryUserSchema
         * @description A user from Google Workspace directory search.
         */
        DirectoryUserSchema: {
            /**
             * Email
             * @description User's email address
             */
            email: string;
            /**
             * Name
             * @description User's display name
             */
            name: string;
            /**
             * Avatar Url
             * @description URL to user's avatar image
             * @default
             */
            avatar_url: string;
        };
        /**
         * CheckoutSessionResponse
         * @description Response with Checkout session URL.
         */
        CheckoutSessionResponse: {
            /** Checkout Url */
            checkout_url: string;
        };
        /**
         * CheckoutSessionRequest
         * @description Request to create a Stripe Checkout session.
         */
        CheckoutSessionRequest: {
            /** Success Url */
            success_url: string;
            /** Cancel Url */
            cancel_url: string;
            /** Quantity */
            quantity?: number | null;
        };
        /**
         * PortalSessionResponse
         * @description Response with Customer Portal URL.
         */
        PortalSessionResponse: {
            /** Portal Url */
            portal_url: string;
        };
        /**
         * PortalSessionRequest
         * @description Request to create a Stripe Customer Portal session.
         */
        PortalSessionRequest: {
            /** Return Url */
            return_url: string;
        };
        /**
         * SubscriptionResponse
         * @description Current subscription status.
         */
        SubscriptionResponse: {
            /** Status */
            status: string;
            /** Quantity */
            quantity: number;
            /** Current Period End */
            current_period_end: string | null;
            /** Cancel At Period End */
            cancel_at_period_end: boolean;
            /** Stripe Customer Id */
            stripe_customer_id: string | null;
        };
        /**
         * SubscriptionIntentResponse
         * @description Response with client secret for Elements payment form.
         */
        SubscriptionIntentResponse: {
            /** Client Secret */
            client_secret: string;
            /** Subscription Id */
            subscription_id: string;
        };
        /**
         * SubscriptionIntentRequest
         * @description Request to create a subscription with payment intent.
         */
        SubscriptionIntentRequest: {
            /** Quantity */
            quantity?: number | null;
        };
        /**
         * ConfirmSubscriptionResponse
         * @description Response after confirming subscription.
         */
        ConfirmSubscriptionResponse: {
            /** Is Active */
            is_active: boolean;
        };
        /**
         * ConfirmSubscriptionRequest
         * @description Request to confirm/sync subscription after payment.
         */
        ConfirmSubscriptionRequest: {
            /** Subscription Id */
            subscription_id: string;
        };
        /**
         * InvoiceListResponse
         * @description List of invoices with pagination info.
         */
        InvoiceListResponse: {
            /** Invoices */
            invoices: components["schemas"]["InvoiceResponse"][];
            /** Has More */
            has_more: boolean;
        };
        /**
         * InvoiceResponse
         * @description Invoice data from Stripe.
         */
        InvoiceResponse: {
            /** Id */
            id: string;
            /** Number */
            number: string | null;
            /** Status */
            status: string;
            /** Amount Due */
            amount_due: number;
            /** Amount Paid */
            amount_paid: number;
            /** Currency */
            currency: string;
            /** Created */
            created: string;
            /** Hosted Invoice Url */
            hosted_invoice_url: string | null;
            /** Invoice Pdf */
            invoice_pdf: string | null;
            /** Period Start */
            period_start: string | null;
            /** Period End */
            period_end: string | null;
        };
        /**
         * UploadResponseSchema
         * @description Response with upload URL and instructions.
         */
        UploadResponseSchema: {
            /**
             * Upload Url
             * @description URL to upload the file to
             */
            upload_url: string;
            /**
             * Method
             * @description HTTP method to use (PUT or POST)
             */
            method: string;
            /**
             * Key
             * @description Storage key for the file
             */
            key: string;
            /**
             * Fields
             * @description Additional form fields for POST uploads
             */
            fields?: {
                [key: string]: string;
            };
        };
        /**
         * UploadRequestSchema
         * @description Request to initiate an image upload.
         */
        UploadRequestSchema: {
            /**
             * Filename
             * @description Original filename with extension
             * @example avatar.jpg
             */
            filename: string;
            /**
             * Content Type
             * @description MIME type of the image
             * @example image/jpeg
             * @example image/png
             * @example image/webp
             */
            content_type: string;
            /**
             * Size Bytes
             * @description File size in bytes
             * @example 102400
             */
            size_bytes: number;
            /**
             * Image Type
             * @description Type of image: 'avatar' or 'logo'
             * @example avatar
             */
            image_type: string;
        };
        /**
         * ImageResponseSchema
         * @description Response with uploaded image details.
         */
        ImageResponseSchema: {
            /**
             * Id
             * @description Image UUID
             */
            id: string;
            /**
             * Url
             * @description Public URL to access the image
             */
            url: string;
            /**
             * Width
             * @description Image width in pixels
             */
            width?: number | null;
            /**
             * Height
             * @description Image height in pixels
             */
            height?: number | null;
        };
        /**
         * ConfirmUploadSchema
         * @description Request to confirm an upload was completed.
         */
        ConfirmUploadSchema: {
            /**
             * Key
             * @description Storage key from the upload response
             */
            key: string;
            /**
             * Image Type
             * @description Type of image: 'avatar' or 'logo'
             */
            image_type: string;
        };
        /**
         * DirectUploadResponseSchema
         * @description Response after direct local upload.
         */
        DirectUploadResponseSchema: {
            /**
             * Key
             * @description Storage key of the uploaded file
             */
            key: string;
            /**
             * Message
             * @description Success message
             */
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    sendMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkSendRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    authenticateMagicLink: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MagicLinkAuthenticateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MagicLinkAuthenticateResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryCreateOrgRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    exchangeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryExchangeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    sendPhoneOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendPhoneOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PhoneOtpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verifyPhoneOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPhoneOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserInfo"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startEmailUpdate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartEmailUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailUpdateResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrganizationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateBilling: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBillingRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDetailResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    inviteMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteMemberResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateMemberRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                member_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchDirectory: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryUserSchema"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getDirectoryAvatar: {
        parameters: {
            query?: {
                url?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createCheckoutSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutSessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createPortalSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalSessionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortalSessionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createSubscriptionIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionIntentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubscriptionIntentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmSubscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmSubscriptionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmSubscriptionResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listInvoices: {
        parameters: {
            query?: {
                limit?: number;
                starting_after?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceListResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requestImageUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequestSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResponseSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirmImageUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmUploadSchema"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponseSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    directUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * File
                     * Format: binary
                     */
                    file: string;
                    /**
                     * Key
                     * @default
                     */
                    key?: string;
                    /**
                     * Content Type
                     * @default
                     */
                    content_type?: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectUploadResponseSchema"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
